### ISSUE TITLE
Filter priority of `passed` and `latest`

### ISSUE THREAD

**Issue by hart323** [amyasnikov/validity#107]
### Validity Version

2.3.3

### NetBox Version

4.0.7

### Python Version

3.11.6

### Steps to Reproduce

1. go to test results
2. apply filter `passed=false and latest=true`

As I thought that filter must show recent status about failed tests for each device. So if device1 failed test1 yesterday and today this device passed this test such filter MUST NOT show this device1 paired with test1 in the list. But it seems like filter first apply `passed` condition which return previous failed results and then apply `latest` condition and as a result we don't get recent test results.

**Summary**:
`device1/test1_passed/today`
`device1/test1_failed/yesterday`
`device1/test1_failed/week_ago`

filter `passed=false and latest=true` applied

**Current and wrong behavior**:
`device1/test1_failed/yesterday`

**Must be**:
`device1/test1_passed/today`

**Comment by amyasnikov** [comment]
Hey @hart323, although you're right that the output is not quite correct, I want to point out the expected result of `latest=True&passed=False` in your case must be no results at all, because the only available latest result is passed while we're looking for failed results.

**Comment by amyasnikov** [comment]
Fixed in #108

**Comment by hart323** [comment]
> I want to point out the expected result of `latest=True&passed=False` in your case must be no results at all

Of course with this filter there must be no results at all, I thought about one thing and wrote about another.
Thanks for the fix!
