### ISSUE TITLE
Error 500 when passing a Serializer from TTP to RouterOS

### ISSUE THREAD

**Issue by aascedu** [amyasnikov/validity#120]
### Validity Version

3.0.2

### NetBox Version

4.1.1

### Python Version

3.12.3

### Steps to Reproduce

Create a serializer using TTP, then changing that TTP Serializer to a RouterOS serializer.
Maybe linked to that : https://github.com/amyasnikov/validity/discussions/119 IDK (definetly not linked but on the same topic of serializer)

### Traceback

![image](https://github.com/user-attachments/assets/263064d8-9328-4843-ad8e-e698d1556420)

**Comment by aascedu** [comment]
Thank you 😄 
Arthur

**Comment by amyasnikov** [comment]
Hey @aascedu, thanks for the issue, fixed
