### ISSUE TITLE
class KeyError 'validity_tests' when running tests

### ISSUE THREAD

**Issue by ArmansPing** [amyasnikov/validity#134]
### Validity Version

3.0.4

### NetBox Version

4.1.3

### Python Version

3.12.3

### Steps to Reproduce

An error occured when "Run Tests"

<class 'KeyError'>

'validity_tests'

Python Version: 3.12.3
NetBox Version: 4.1.3
Plugins: 
  netbox_napalm_plugin: 0.3.0
  validity: 3.0.4

**Comment by amyasnikov** [comment]
Hey @ArmansPing, please provide the following info:
1. Traceback of the error. You can find it in the terminal (depending on your installation you can use something like `docker logs` or `journalctl -u`)
2. Detailed sequence of the steps to reproduce the error on a clean netbox/validity setup.

Without both of these points I can't reproduce (and fix) the error.

**Comment by ArmansPing** [comment]
1. "docker compose logs -f netbox" info are below:
netbox-1  | 172.18.66.66 - - [16/Oct/2024:02:18:39 +0000] "GET /plugins/validity/tests/run/ HTTP/1.1" 500 1554 "http://172.30.248.2:8000/plugins/validity/tests/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0"
netbox-1  | 172.18.66.66 - - [16/Oct/2024:02:18:39 +0000] "GET /static/netbox-light.css HTTP/1.1" 404 54 "http://172.30.248.2:8000/plugins/validity/tests/run/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0"
netbox-1  | ::1 - - [16/Oct/2024:02:18:43 +0000] "GET /login/ HTTP/1.1" 200 3260 "-" "curl/8.5.0"

2. This error occured when I try to validate the ntp status of a huawei_ce switch. Here is the raw text of the file "{{device.name}}.cfg":
```
clock status: synchronized
 clock stratum: 4
 reference clock ID: 172.30.255.4 
 nominal frequency: 100.0000 Hz
 actual frequency: 100.0000 Hz
 clock precision: 2^17
 clock offset: -6.0197 ms
 root delay: 40.60 ms
 root dispersion: 41.01 ms
 peer dispersion: 2.82 ms
 reference time: 07:47:53.265 UTC Oct 14 2024(EAB74B29.440FECDD)
 synchronization state: clock synchronized
```
  Detailed steps to trigger this error:
  1. Create a local data source with URL"file:///opt/netbox/netbox/data/validity/" and Config Path "{{device.name}}.cfg"
  2. Create a Selector and config a site filter, other parameters are default
  4. Create a Serializer with method "TTP" to translate "{{device.name}}.cfg" into yaml format. I can see the data is correctly translated at the device's Serialized State tab. 
the TTP expression:
```
<group name="ntp">
 clock status: {{ status }}
 reference clock ID: {{ server }}
</group>
```
the device's Serialized State data
```
ntp:
  server: 172.30.255.4
  status: synchronized
```
  5. Create a Test and choose the Selector at the second step created. Then type the expressions
 ```
jq.first('.ntp.status', device.config) == 'synchronized'
```

All steps are here. Then I press "Run Tests" button，the error will occured.

**Comment by ArmansPing** [comment]
Hi, I enabled the debug mode of netbox, belows are the traceback:

netbox-1  | Internal Server Error: /plugins/validity/tests/run/
netbox-1  | Traceback (most recent call last):
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
netbox-1  |     response = get_response(request)
netbox-1  |                ^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
netbox-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
netbox-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 97, in view
netbox-1  |     self = cls(**initkwargs)
netbox-1  |            ^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/dimi/di.py", line 102, in sync_wrapper
netbox-1  |     kwargs |= {kw.name: kw.getattrs(self._deps.resolve(kw.func)) for kw in extra_kwargs}
netbox-1  |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/dimi/_storage.py", line 70, in resolve
netbox-1  |     return self._resolve_sync(key)()
netbox-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/dimi/dependency.py", line 54, in __call__
netbox-1  |     return self.scope(**self.resolved)
netbox-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/dimi/scopes.py", line 93, in _call
netbox-1  |     return super()._call(*args, **kwargs)
netbox-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/dimi/scopes.py", line 55, in _call
netbox-1  |     result = self.func(*args, **kwargs)
netbox-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/validity/dependencies.py", line 55, in runtests_launcher
netbox-1  |     rq_queue=django_rq.get_queue(vsettings.runtests_queue),
netbox-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1  |   File "/opt/netbox/venv/lib/python3.12/site-packages/django_rq/queues.py", line 172, in get_queue
netbox-1  |     is_async = QUEUES[name].get('ASYNC', True)
netbox-1  |                ~~~~~~^^^^^^
netbox-1  | KeyError: 'validity_tests'

**Comment by amyasnikov** [comment]
@ArmansPing the error was caused by custom queue name for running tests (`validity_tests`), which did not exist. You can either wait for the next release to get this fixed or just use an existing queue name (e.g. `default` or `high`) as a workaround
