### ISSUE TITLE
misc project maintenance

### ISSUE THREAD

**Issue by ryanmerolle** [amyasnikov/validity#34]
- Add netbox-plugin to the github project topics so people can find it
- Update the README to include the plugin config settings as listed [here ](https://github.com/amyasnikov/validity/blob/6fe36fd278e0cf441466611c44d3ae075dcb6e7c/development/configuration.py#L62-L64)
- mention the pypi package name so we can link on https://netbox.dev/ and associate to our tracker

**Comment by amyasnikov** [comment]
_* Add netbox-plugin to the github project topics so people can find it_
**done**

_* Update the README to include the plugin config settings as listed here_
Is it mandatory? I already have a separate docs page describing all the settings, see [here](https://validity.readthedocs.io/en/latest/plugin_settings/). I think this is the more convenient way.

_* mention the pypi package name so we can link on https://netbox.dev/ and associate to our tracker_
**netbox-validity**

**Comment by ryanmerolle** [comment]
Nothing is mandatory.  It was more some helpers to make things easy for people. I did not realize you had the plugin config documented already. Thanks!
