### ISSUE TITLE
NetBox 3.5 Data Sources

### ISSUE THREAD

**Issue by ryanmerolle** [amyasnikov/validity#36]
Replace you functionality to sync data sources from git, with the newly implemented [NetBox 3.5 Data Sources](https://github.com/netbox-community/netbox/issues/11558).

NetBox 3.5.0 gets released this week, but can be tested/developed on using `docker pull netboxcommunity/netbox:v3.5-beta2`

This would allow you to remove unneeded code

**Comment by amyasnikov** [comment]
Yeah, I'm definitely going to do it in one of the future releases.
It was a bit unlucky for me to implement git communication in parallel with core NetBox.

**Comment by ryanmerolle** [comment]
I actually was just told it’s not officially supported for plugins to use yet.

**Comment by amyasnikov** [comment]
Done within #52
