### ISSUE TITLE
Set TAG based on config snippet

### ISSUE THREAD

**Issue by PieterL75** [amyasnikov/validity#51]
I would love to see the feature to be able to set a TAG on a device, based on a config snippet.
for example: All Fortigate's that have SSLVPN enabled should get the 'FGT SSLVPN' tag automatically set or removed

**Comment by amyasnikov** [comment]
If I understand you right you want to assign/remove tags to devices according to the presence/absence of some data in the device serialized configuration.
Unfortunately, it's not the purpose of Validity to rule or change inventory data like tags or any other device properties. The only purpose of Validity is to check device configurations for errors. I would be happy to implement new features which are compliant to this main goal.

The option I'd suggest you is to write your own NetBox custom script and leverage Validity config serialization feature there. Something like this:
```
from validity.models import VDevice  # this is the proxy model to NetBox Device
from extras.models import Tag

fortigates = VDevice.objects.filter(device_type__manufacturer__slug='fortigate')
fortigates = fortigates.annotate_json_serializer().annotate_json_repo()  # this is required to avoid extra db queries

vpn_tag = Tag.objects.get(name='SSLVPN')

for device in fortigates:
    if 'ssl' in device.config['vpn']:  # device.config stores serialized config
        device.tags.add(vpn_tag)
    else:
        device.tags.remove(vpn_tag)
```
